Moving notify-recipients at the beginning of pipeline
notify-recipients must be executed as soon as possible - if error
happens somewhere in the pipeline, notify-email will ask for recipients,
and since notify-recipients was placed right before notify-email, it'd
be executed by the time of crash - and its shared functions wouldn't be
registered either, which leads to this:

[11:17:24] [E] error in destroy function: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/var/lib/jenkins/virtualenv-citool/lib/python2.7/site-packages/citool-0.1-py2.7.egg/libci/ci.py", line 741, in destroy_modules
    module.destroy(failure=failure)
  File "/var/lib/jenkins/virtualenv-citool/lib/python2.7/site-packages/citool-0.1-py2.7.egg/libci/modules/helpers/notify_email.py", line 547, in destroy
    recipients = ['{}@redhat.com'.format(user) for user in self.shared('notification_recipients')]
TypeError: 'NoneType' object is not iterable